services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
      - PORT=3002
      - CORS_ORIGINS=http://localhost:3002,https://tasks.fmarcos.dev
      - PINO_LOG_LEVEL=info
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=100
    volumes:
      - ./src:/app/src
    command: pnpm dev
