export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  TODOIST_API_TOKEN: 'TODOIST_API_TOKEN',
  CACHE_TTL_SECONDS: 'CACHE_TTL_SECONDS',
  CORS_ORIGINS: 'CORS_ORIGINS',
  PINO_LOG_LEVEL: 'PINO_LOG_LEVEL',
  THROTTLE_TTL: 'THROTTLE_TTL',
  THROTTLE_LIMIT: 'THROTTLE_LIMIT',
} as const;

export type EnvKey = (typeof ENV_KEYS)[keyof typeof ENV_KEYS];
